apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "stockit-backend-chart.fullname" . }}-backendconfig
  labels:
    {{- include "stockit-backend-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.backend.name }}
spec:
  healthCheck:
    requestPath: {{ .Values.backend.probe.path }}
    port: {{ .Values.backend.service.port }}
    timeoutSec: {{ default 5 .Values.backend.probe.timeoutSeconds }}
  # HTTP를 HTTPS로 리다이렉트 (HTTPS만 허용)
  redirectToHttps: true

