spring:
  config:
    import: optional:file:..env[.properties]

  data:
    redis:
      host: localhost  # 로컬 환경에서는 localhost 사용
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true # 이 설정 추가
  sql:
    init:
      mode: never # DB 초기화 스크립트(data.sql)를 '항상' 실행